name: Terraform IaC Workflow

on:
  push:
    branches:
      - main

env:
  SLACK_CHANNEL: '#iac-reports'
  LAST_ERROR_FILE: last_error.log
  PY_VENV: .venv
  PY_SCRIPT_PLAN: iac_review_bedrock-plan.py
  PY_SCRIPT_ERROR: iac_review_bedrock.py

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout Repository
        uses: actions/checkout@v3

      - name: ⚙️ Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: 🔐 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1

      - name: 📦 Terraform Init
        run: terraform init 2> ${{ env.LAST_ERROR_FILE }}

      - name: ✅ Terraform Validate
        run: terraform validate 2> ${{ env.LAST_ERROR_FILE }}

      - name: 📄 Terraform Plan
        run: |
          terraform plan -out=tfplan.binary 2> ${{ env.LAST_ERROR_FILE }}
          terraform show -json tfplan.binary > plan.json

      - name: 💰 Infracost Breakdown
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        run: |
          infracost breakdown --path plan.json --format json --out-file infracost_output.json
          infracost breakdown --path plan.json --format table > infracost_summary.txt

      - name: 🤖 Run AI Code Review Script (Plan Success Path)
        run: |
          python3 -m venv ${{ env.PY_VENV }}
          source ${{ env.PY_VENV }}/bin/activate
          pip install --upgrade pip boto3 botocore
          python ${{ env.PY_SCRIPT_PLAN }} "${{ github.workspace }}"

      - name: 📣 Send Slack Summary on Success
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          SUMMARY=$(head -c 3500 infracost_summary.txt)
          REPORT=$(head -c 3500 iac_code_review_bedrock.md)
          MESSAGE="💸 *Infracost Estimate:*\n\`\`\`${SUMMARY}\`\`\`\n\n🤖 *AI Code Review & Remediation Suggestions:*\n${REPORT}"
          curl -X POST -H "Authorization: Bearer $SLACK_BOT_TOKEN" -H 'Content-type: application/json' \
            --data "{\"channel\": \"${{ env.SLACK_CHANNEL }}\", \"text\": \"$MESSAGE\"}" \
            https://slack.com/api/chat.postMessage

      - name: ⚠️ Terraform Apply Dummy
        run: echo "This is a dummy apply. No real infrastructure will be changed."

      - name: ❌ Run Error Script on Failure
        if: failure()
        run: |
          python3 -m venv ${{ env.PY_VENV }}
          source ${{ env.PY_VENV }}/bin/activate
          pip install --upgrade pip boto3 botocore
          ERR_MSG=$(cat ${{ env.LAST_ERROR_FILE }})
          python ${{ env.PY_SCRIPT_ERROR }} "${{ github.workspace }}" "$ERR_MSG"

      - name: 📣 Send Slack Error Report
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          REPORT=$(head -c 30000 iac_code_review_bedrock.md)
          curl -X POST -H "Authorization: Bearer $SLACK_BOT_TOKEN" -H 'Content-type: application/json' \
            --data "{\"channel\": \"${{ env.SLACK_CHANNEL }}\", \"text\": \"🤖 *AI Code Review & Remediation Suggestions:*\n\n${REPORT}\n\nSee GitHub Actions for details.\"}" \
            https://slack.com/api/chat.postMessage
